# This is a basic workflow to help you get started with Actions

name: ADV-IT_SDI-IT_CI_MyGitHubActionsBasics
env:
  APPLICATION_NAME : "MyFlask"
  PACKAGE_NAME     : "flask-deploy-ver-${{ github.sha }}"

on:
  push:
    branches:
    - master

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message from testing
        run: echo "Hello, world from testing job!"
      
      - name: Execute few commands
        run: 
          echo "Hello message 1"
          echo "Hello message 2"
          echo "Application name is ${{ env.APPLICATION_NAME }}"
      
      - name: list current folder
        run: ls -la
        
      - name: Git clone my repo
        uses: actions/checkout@v1
        
      - name: list current folder
        run: ls -la
          
          
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
      - name: Print Hello Message from Deploy
        run: echo "Hello, world from deploy job!"
        
      - name: Printing Deployment package
        run: 
          echo "Deploy package name is ${{ env.PACKAGE_NAME }}"
          
      - name: Lets test some packages if they are here 1
        run: aws --version
        
      - name: Lets test some packages if they are here 2
        run: zip

